# WhatATheme
markdown: kramdown

# URL of the Site
url: stellema.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Annette Stellema
# Description of the Site
description: Physical Oceanographer / Climate Scientist
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Stellema, Annette
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /stellema.github.io/assets/images/Iceland.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: a.stellema@unsw.edu.au
facebook_username:
twitter_username:
instagram_username: stellerama
linkedin_username: astellema
github_username: stellema
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:
googlescholar_username: citations?hl=en&user=2uqlcxcAAAAJ

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Annette Stellema
# URL for the Image of the Author
author-image: /stellema.github.io/assets/images/AuthorImage.jpg
# 60 Words About the Author
author-about: Hi, I'm a PhD Candidate at the Climate Change Research Centre at the University of New South Wales in Sydney, Australia.
My primary research interest is understanding how and why the circulation of the ocean are projected to change in a future, warmer world.
I have investigated the expected future changes of ocean currents in the Pacific and Indian Ocean and the major western boundary currents including the Gulf Stream, Kuroshio Current and East Australian Current using over 60 coupled climate models.
My current research examines the projected changes of source waters and biogeochemistry pathways in the equatorial Pacific using particle-tracking methods.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/stellema

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
