markdown: kramdown

# URL of the Site
url: "https://stellema.github.io"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Annette Stellema
# Description of the Site
description: Climate Science / Physical Oceanography PhD Student
# URL of Image of the Site
site-image: /assets/images/shifaaz-shamoon-sLAk1guBG90-unsplash.jpg
# Keywords of the Site
site-keywords: Stellema, Annette
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/shifaaz-shamoon-sLAk1guBG90-unsplash.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: a.stellema@unsw.edu.au
facebook_username:
twitter_username:
instagram_username:
linkedin_username: astellema
github_username: stellema
youtube_channel_id: UCDgHYaKXWDQHFJ_030FuJrQ
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Annette Stellema
# URL for the Image of the Author
author-image: /assets/images/AuthorImage.jpg
# 60 Words About the Author
author-about: >
  PhD Candidate at the Climate Change Research Centre, UNSW, Sydney, Australia.
  <br/><br/>
  <strong>About</strong>
  <br/><br/>
  My research interests include understanding how climate change will impact ocean circulation and biogeochemistry, 
  developing software tools for climate research and improving climate models.
  <br/><br/>
  My PhD research examines model representation and future changes of circulation and iron in the tropical Pacific. 
  I used particle-tracking methods to understand how the complex mix of multi-decadal projected changes in this region are connected. 
  I also simuated the effects of circulation changes on nutrient supply to the equatorial Pacific by developing a semi-Lagrangian iron model.
  <br/><br/>
  Previously, I investigated the expected future changes of ocean currents in the Pacific
  and Indian Ocean and the major western boundary currents including the Gulf Stream,
  Kuroshio Current and East Australian Current using over 60 coupled climate models.
  <br/><br/>
  I am in the final year of a PhD in Climate Science and completed a Bachelor of Science majoring in
  Physics and Maths (Physical Oceanography) with honours in Climate Science at UNSW, Sydney.
  <br/><br/>
  Please contact me if you would like to discuss my research on ocean circulation, CMIP and observational datasets, teaching resources for marine heatwaves or python code for particle-tracking experiments.
  <br/><br/>

  <strong>Publications</strong>
  <br/><br/>
  Stellema, A., Sen Gupta, A., Taschetto, A.S. & Feng, M. (2022). Pacific Equatorial Undercurrent: Mean-state, sources, and future changes. Frontiers in Climate, 4,<a href="https://www.frontiersin.org/articles/10.3389/fclim.2022.933091/full">https://www.frontiersin.org/articles/10.3389/fclim.2022.933091/full</a>
  <br/><br/>
  Sen Gupta, A., Stellema, A., Pontes, G.M., Vergés, A., Rossi, V. (2021). Future changes to the upper ocean Western Boundary Currents across two generations of climate models. Scientific Reports, 11, 9538.<a href="https://doi.org/10.1038/s41598-021-88934-w">https://doi.org/10.1038/s41598-021-88934-w</a>
  <br/><br/>
  Stellema, A., Sen Gupta, A. & Taschetto, A.S. (2019). Projected slow down of South Indian Ocean circulation. Scientific Reports. 9, 17705.<a href="https://doi.org/10.1038/s41598-019-54092-3">https://doi.org/10.1038/s41598-019-54092-3</a>
  <br/><br/>

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/stellema

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
